#!/usr/bin/env python3
"""Recompute judge-vs-human agreement against Carlos's refreshed gold-standard
labels — WITHOUT re-running the judge.

Why this is correct (not a shortcut): the judge never sees the human labels, so
its per-criterion verdicts (`results.json` -> cases[].results) are a *fixed*
artifact. Only the gold standard changed (Carlos completed the 13 uncollected
cases and added genuine False variance on `grounded` / `appropriately-hedged`).
Re-scoring the frozen verdicts against the new labels is the exact,
reproducible thing to do; re-invoking the LLM would only inject fresh
nondeterminism into a comparison whose judge side we want held constant.

The label-independent blocks (bias probes, cost/latency) are carried forward
from the committed judge run unchanged — they do not depend on the labels.

Agreement/κ and the disagreement rows are recomputed with the *tested*
`eval_judge.report` functions (per_criterion_agreement, disagreements,
cohen_kappa), so no metric math is reinvented here.
"""
from __future__ import annotations

import json
from pathlib import Path

from eval_judge.judge import JudgeVerdict
from eval_judge import report

HERE = Path(__file__).resolve().parent
RESULTS = HERE / "results" / "results.json"
LABELS = HERE / "labels" / "calibration_responses.json"


SUMMARY = None  # set in main


def _write_summary(new: dict, agreement: dict, dis: list, n_labeled: int) -> None:
    p = HERE / "results" / "SUMMARY.md"
    cl = new["cost_latency"]
    pr = new["probes"]
    L = []
    L.append(f"# LLM-as-judge — calibration results\n")
    L.append(f"**Target:** `{new['target']}`  ")
    L.append(f"**Cases judged:** {cl['n']}  |  **Cases labeled:** {n_labeled}  "
             f"(15 collected + labeled after this judge run; judge pass on them "
             f"pending, needs `OPENROUTER_API_KEY`)  ")
    L.append(f"**Judge held constant; gold standard refreshed {new['relabeled_at']}.**\n")

    L.append("## Judge-vs-human agreement\n")
    L.append("| Criterion | n | Agreement | Cohen's κ |")
    L.append("|---|---|---|---|")
    order = ["grounded", "complete", "appropriately-hedged", "usable"]
    for c in order:
        a = agreement[c]
        if a["n"]:
            L.append(f"| {c} | {a['n']} | {a['agreement_rate']:.0%} | {a['kappa']:.2f} |")
        else:
            L.append(f"| {c} | 0 | N/A | N/A |")
    L.append("")

    by_crit: dict[str, int] = {}
    for r in dis:
        by_crit[r["criterion"]] = by_crit.get(r["criterion"], 0) + 1
    L.append(f"## Disagreements (judge vs. human): {len(dis)} rows\n")
    L.append("By criterion: " + ", ".join(f"{k} {v}" for k, v in by_crit.items()) + "\n")
    L.append("| Case | Criterion | Judge | Human |")
    L.append("|---|---|---|---|")
    for r in dis:
        L.append(f"| {r['case_id']} | {r['criterion']} | {r['judge']} | {r['human']} |")
    L.append("")

    L.append("## Bias probes\n")
    L.append("| Probe | Flagged | Total |")
    L.append("|---|---|---|")
    for k, v in pr.items():
        L.append(f"| {k} | {v['flagged']} | {v['total']} |")
    L.append("")

    L.append("## Cost & latency\n")
    L.append(f"- Judged: {cl['n']} cases")
    L.append(f"- Total cost: ${cl['total_cost_usd']}")
    L.append(f"- Latency: p50 {cl['p50_latency_ms']:.0f} ms / p95 {cl['p95_latency_ms']:.0f} ms\n")
    L.append("_Carlos is the sole human labeler (disclosed, not hidden). Judge "
             "prompt is versioned in `judge_prompts/`. These numbers are "
             "regenerated by `regenerate_report.py` whenever labels change; the "
             "judge verdicts themselves come from the committed run in "
             "`results.json`._")
    p.write_text("\n".join(L))


def main() -> None:
    old = json.loads(RESULTS.read_text())
    labels_list = json.loads(LABELS.read_text())
    human_labels = {c["id"]: c["human_labels"] for c in labels_list
                    if c.get("human_labels") is not None}

    # Reconstruct the frozen judge verdicts from the committed run. Per-case
    # latency/cost aren't stored per row (only the aggregate is), so we carry
    # the aggregate cost/latency block forward rather than recompute it.
    verdicts = [
        JudgeVerdict(
            case_id=c["id"],
            prompt_version=c.get("prompt_version", "v1"),
            results=c["results"],
            reasons=c.get("reasons", {}),
        )
        for c in old["cases"]
    ]

    agreement = report.per_criterion_agreement(verdicts, human_labels)
    dis = report.disagreements(verdicts, human_labels)

    new = dict(old)
    new["run_at"] = old.get("run_at")
    new["relabeled_at"] = "2026-07-20"  # gold standard refreshed; judge held constant
    new["agreement"] = agreement
    new["disagreements"] = dis
    # probes + cost_latency preserved from the judge run (label-independent)
    new["cases"] = [
        {**c, "human_labels": human_labels.get(c["id"])}
        for c in old["cases"]
    ]
    RESULTS.write_text(json.dumps(new, indent=2))
    _write_summary(new, agreement, dis, len(human_labels))

    # Console summary
    print(f"Judged cases: {len(verdicts)}  |  labeled cases: {len(human_labels)}")
    print(f"Unjudged-but-labeled: {len(human_labels) - len(verdicts)} "
          "(collected + labeled; judge pass pending, needs OPENROUTER_API_KEY)\n")
    print(f"{'criterion':22} {'n':>3} {'agree':>7} {'kappa':>7}")
    for c, a in agreement.items():
        if a["n"]:
            print(f"{c:22} {a['n']:>3} {a['agreement_rate']:>6.0%} {a['kappa']:>7.2f}")
    print(f"\nDisagreement rows: {len(dis)}")
    by_crit: dict[str, int] = {}
    for r in dis:
        by_crit[r["criterion"]] = by_crit.get(r["criterion"], 0) + 1
    print("by criterion:", by_crit)


if __name__ == "__main__":
    main()
